[project]
name = "crew-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "crewai[tools]",
    "notebook>=7.4.4",
    "python-dotenv>=1.1.1",
]
